### ISSUE TITLE
ImprovedTransactionData: node.removeLabel doesn't affect getAllChangedNodes()

### ISSUE THREAD

**Issue by jazzido** [graphaware/neo4j-framework#17] opened 2015-05-19 19:47 UTC
I'm using `tx-api` to [integrate Neo4J with ElasticSearch](https://github.com/jazzido/neo4j-elasticsearch/blob/graphaware-tx-api/src/main/java/org/neo4j/elasticsearch/ElasticSearchEventHandler.java) and came across a (possible) issue.

When the only mutation performed to a `Node` is `removeLabel()`, `getAllChangedNodes()` won't contain the corresponding entry. Namely:

```java
tx = db.beginTx();
node = db.getNodeById(Integer.parseInt(id));
Iterator<Label> labels = node.getLabels().iterator();
assertEquals(DynamicLabel.label("Label"), labels.next());
assertEquals(DynamicLabel.label("OtherLabel"), labels.next());
node.removeLabel(DynamicLabel.label(LABEL));
tx.success(); tx.close();
```
`ImprovedTransactionData.getAllChangedNodes()` in the `beforeCommit` handler for this transaction, is empty.

**Comment by bachmanm** [comment] 2015-05-19 21:50
Hey, first of all, thanks for working on the ElasticSearch integration and for using the GraphAware Framework, good effort!

Now, there was a bug in `FilteredTransactionData`, which I've fixed and which will be released soon, but I don't think it affects you since you're using `LazyTransactionData`. What you're seeing could be a bug, indeed, but I haven't managed to reproduce it yet.

It could also be another thing. In your test (from your codebase, not the one attached to this issue), you're creating a label, then removing it. The creation of the label will trigger a transaction commit (event before that label is assigned to the node). This commit has no changes in it from `ImprovedTransactionData`'s point of view. For more info, see http://stackoverflow.com/questions/30052000/is-this-a-normal-behavior-for-a-transactioneventhandler/30156657#30156657

Could you do me a favour and check that your transaction event handler isn't called again (after it has been called once with no changes) with the correct result in `getAllChangedNodes()`?

Cheers!

P.S.: Your code I'm referring to is:

```
    @Test
    public void testRemoveLabel() throws Exception {
        Transaction tx = db.beginTx();
        org.neo4j.graphdb.Node node = db.createNode(DynamicLabel.label(LABEL), DynamicLabel.label("OtherLabel"));
        String id = String.valueOf(node.getId());
        node.setProperty("foo","baz");
        tx.success();tx.close();
        
        JestResult response = client.execute(new Get.Builder(INDEX, id).build());
        Map source = response.getSourceAsObject(Map.class);
        assertEquals(true,response.isSucceeded());
        assertEquals("baz", source.get("foo"));
        
        tx = db.beginTx();
        node = db.getNodeById(Integer.parseInt(id));
        node.removeLabel(DynamicLabel.label(LABEL));
        tx.success(); tx.close();
        
        response = client.execute(new Get.Builder(INDEX, id).build());
        source = response.getSourceAsObject(Map.class);
        assertEquals(false, response.getValue("found"));
    }
```

**Comment by jazzido** [comment] 2015-05-20 02:25
> Hey, first of all, thanks for working on the ElasticSearch integration and for using the GraphAware Framework, good effort!

Thank you. I've only implemented some of the suggestions made by @jexp on his project's README. GA Framework is very handy for providing an —IMHO— better API for tracking changes.

> Now, there was a bug in FilteredTransactionData, which I've fixed and which will be released soon, but I don't think it affects you since you're using LazyTransactionData. What you're seeing could be a bug, indeed, but I haven't managed to reproduce it yet.

Actually, I reported this issue before I started using `LazyTransactionData` instead of `FilteredTransactionData`, so I might have been bitten by the bug you mention. See [this revision of my transaction handler](https://github.com/jazzido/neo4j-elasticsearch/blob/3ab4ee18ba314d3916ad089edf260a7fb446bb0a/src/main/java/org/neo4j/elasticsearch/ElasticSearchEventHandler.java).

> It could also be another thing. [...] The creation of the label will trigger a transaction commit (event before that label is assigned to the node). Could you do me a favour and check that your transaction event handler isn't called again (after it has been called once with no changes) with the correct result in getAllChangedNodes()?

Please see [this version](https://gist.github.com/jazzido/9369d7134a8acb64be54) of my transaction handler which outputs debug messages in the `beforeCommit` method. The output produced by [`testRemoveProperty()`](https://github.com/jazzido/neo4j-elasticsearch/blob/3ab4ee18ba314d3916ad089edf260a7fb446bb0a/src/test/java/org/neo4j/elasticsearch/ElasticSearchEventHandlerTest.java#L141) is:

```
beforeCommit call count: 1
---
beforeCommit call count: 2
---
beforeCommit call count: 3
---
beforeCommit call count: 4
  created node
---
beforeCommit call count: 5
  node change
  removed label: OtherLabel
---
```

Thanks again!

**Comment by jazzido** [comment] 2015-05-20 18:58
What's the intended behaviour for node label removal if `FilteredTransactionData` filters out nodes that does not have the label that has just been removed? In other words, does `NodeInclusionPolicy.include(node)` gets the current or previous version of a node as its argument?

**Comment by bachmanm** [comment] 2015-05-23 01:28
The intended behaviour is that it will get picked up. The inclusion policy is presented with both the previous and current version of the node and if it returns true for any of the, it gets picked up.

Please see
https://github.com/graphaware/neo4j-framework/blob/master/tx-api/src/test/java/com/graphaware/tx/event/improved/FilteredLazyTransactionDataIntegrationTest.java#L141

and

https://github.com/graphaware/neo4j-framework/blob/master/tx-api/src/main/java/com/graphaware/tx/event/improved/data/filtered/FilteredPropertyContainerTransactionData.java#L315

I'm closing this issue for now, please let me know if you still have problems. From your last comment, I got the impression that it is working. The bug with FilteredTransactionData has been fixed. Cheers

**Closed by bachmanm** 2015-05-23 01:28 UTC
